# Generated by Django 3.1.7 on 2021-03-04 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
                ('item_quantity', models.CharField(max_length=100)),
                ('item_status', models.CharField(choices=[('Pending', 'Pending'), ('Bought', 'Bought'), ('Not Available', 'Not Available')], max_length=100)),
                ('date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopping list',
                'verbose_name_plural': 'Shopping list',
            },
        ),
    ]
